micronaut:
  application:
    name: restApi
  http:
    client:
      read-idle-timeout: 10m

grpc:
  client:
    plaintext: true
    max-retry-attempts: 5
  channels:
    keyManager:
      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}'
